### ISSUE TITLE
Mining level/tool

### ISSUE THREAD

**Issue by Staegrin** [MehVahdJukaar/vertical_slab_compat#27]
So versions: v_slab_compat-1.20-2.1
minecraft 1.20.1
Neoforge 47.1.76
Description: Vertical slabs have no matching appropriate tool and when broken don't always drop anything

![2023-12-21_18 31 04](https://github.com/MehVahdJukaar/vertical_slab_compat/assets/8494635/cacc9908-f89e-48d4-9cbf-26bc377942bc)
So in the picture an oak vertical slab The One Probe says an iron axe is not the right tool. The tool will indeed break it and drop the slab item.

![2023-12-21_18 31 15](https://github.com/MehVahdJukaar/vertical_slab_compat/assets/8494635/8b6f6059-84bb-4093-a479-e4095bcc4973)
But for stone based vertical slabs even when broken with a netherite pickaxe they will not drop anything.
![2023-12-21_18 41 29](https://github.com/MehVahdJukaar/vertical_slab_compat/assets/8494635/a825fab3-b14f-4456-aa0e-ca2ec72515a0)
The Only metal based vertical slab I can break that drops anything is the electrum sheetmetal slab
![2023-12-21_18 50 09](https://github.com/MehVahdJukaar/vertical_slab_compat/assets/8494635/08b6d960-365a-4d8c-936f-501bd1e935d7)

Can use a mining laser from Direwolf20's Mining Gadget mod. to mine all slabs...

**Comment by Staegrin** [comment]
Latest update v_slab_compat-1.20-2.2 has made it so wooden slabs also no longer drop when broken
Mining Laser can also no longer break and create the item version.

**Comment by MehVahdJukaar** [comment]
I can't replicate this. See if you have errors on your log

**Comment by Staegrin** [comment]
Placed 32 Vertical slabs Broke them with the mining laser
Checked logs
console
debug
latest
Nothing shows up on any of the three

**Comment by Staegrin** [comment]
Placed 32 Vertical slabs Broke them with the mining laser
Checked logs
console 
https://gist.github.com/Staegrin/22b28e94523a4c4bdcac613e2f3fd86a
debug
https://gist.github.com/Staegrin/0fc306dfbb3123a34aeaeb7447d34609
latest
https://gist.github.com/Staegrin/3320e077cd1443170be78d1e3388734f
Nothing shows up on any of the three

**Comment by Staegrin** [comment]
Did a clean install. Breaking worked fine with just 
v_slab_compat-1.20-2.2
moonlight-1.20-2.8.67-forge
mininggadgets-1.15.6
jei-1.20.1-forge-15.2.0.27
Going to have to go through all mods to find the mod causing conflicts with vertical slabs

**Comment by Staegrin** [comment]
Found the culprit
create-1.20.1-0.5.1.f
With create installed Vertical slabs no longer drop when broken

**Comment by MehVahdJukaar** [comment]
Illl need to do some testing

**Comment by Staegrin** [comment]
v_slab_compat-1.20-2.3 seems to have fixed this issue
