### ISSUE TITLE
Slabs don't have any crafting recipies: 1.20.1

### ISSUE THREAD

**Issue by BetaKale** [MehVahdJukaar/vertical_slab_compat#30]
For some reason I'm unable to craft any of the vertical slabs on my server, even rei won't show the crafting recipies. If this is just a mod conflict let me know.

**Comment by kirgo0** [comment]
I have this problem right now.

**Comment by kirgo0** [comment]
It also doesn't work in the default survival world, you can't craft vertical slabs, and if you place them in creative mode and then try to mine them in survival mode, nothing will drop out :(

**Comment by Staegrin** [comment]
This happened after the latest update (v_slab_compat-1.20-2.1 -> v_slab_compat-1.20-2.2). Before most of the vertical slabs were craftable. But having the create mod (create-1.20.1-0.5.1.f) and this mod together also makes it so the slabs can't be mined/gathered for some reason.

**Comment by Staegrin** [comment]
v_slab_compat-1.20-2.3 seems to have fixed this issue
