### ISSUE TITLE
Missing slabs

### ISSUE THREAD

**Issue by jukarr** [MehVahdJukaar/vertical_slab_compat#5]
The mod seems to be missing some vanilla blocks - such as stone bricks, deepslate tiles. Additionally, BetterEnd ones are missing textures.

**Comment by MehVahdJukaar** [comment]
Better end can't be supported as they register many of their blocks dynamically even tho most don't change. It conceptually can't work as vertical slabs are dynamic themselves. As for vanilla stuff are you sure you don't have a mod that adds them already? Last time I checked they all worked

**Comment by jukarr** [comment]
I do have a separate mod that adds the BetterEnd ones, but they shouldn't interfere with vanilla slabs, right? They both have cracked versions, but not the normal ones. I checked the creative menu, give menu and REI and they don't appear on any of them surprisingly.

**Comment by MehVahdJukaar** [comment]
No they shouldn't but it's worth a try
